export const skillCategories = [
  {
    id: "frontend",
    label: "Frontend",
    icon: "🎨",
    desc: "UI & Client-side development",
    skills: [
      { id: "html", label: "HTML", icon: "🟧" },
      { id: "css", label: "CSS", icon: "🟦" },
      { id: "js", label: "JavaScript", icon: "🟨" },
      { id: "ts", label: "TypeScript", icon: "🔷" },
      { id: "react", label: "React", icon: "⚛️" },
      { id: "vue", label: "Vue.js", icon: "🟩" },
      { id: "angular", label: "Angular", icon: "🔴" },
      { id: "tailwind", label: "Tailwind CSS", icon: "🌊" },
      { id: "nextjs", label: "Next.js", icon: "▲" },
      { id: "sass", label: "Sass", icon: "🎨" },
    ],
  },
  {
    id: "backend",
    label: "Backend",
    icon: "⚙️",
    desc: "Server-side & APIs",
    skills: [
      { id: "nodejs", label: "Node.js", icon: "🟢" },
      { id: "python", label: "Python", icon: "🐍" },
      { id: "java", label: "Java", icon: "☕" },
      { id: "php", label: "PHP", icon: "🐘" },
      { id: "go", label: "Go", icon: "🔵" },
      { id: "rust", label: "Rust", icon: "🦀" },
      { id: "express", label: "Express", icon: "🚂" },
      { id: "django", label: "Django", icon: "🎯" },
      { id: "graphql", label: "GraphQL", icon: "🔗" },
    ],
  },
  {
    id: "database",
    label: "Database",
    icon: "🗄️",
    desc: "Data storage & queries",
    skills: [
      { id: "mongodb", label: "MongoDB", icon: "🍃" },
      { id: "mysql", label: "MySQL", icon: "🐬" },
      { id: "postgres", label: "PostgreSQL", icon: "🐘" },
      { id: "redis", label: "Redis", icon: "🔴" },
      { id: "firebase", label: "Firebase", icon: "🔥" },
      { id: "sqlite", label: "SQLite", icon: "💾" },
    ],
  },
  {
    id: "other",
    label: "DevOps & Other",
    icon: "☁️",
    desc: "Infrastructure & tools",
    skills: [
      { id: "git", label: "Git", icon: "🌿" },
      { id: "docker", label: "Docker", icon: "🐳" },
      { id: "aws", label: "AWS", icon: "☁️" },
      { id: "linux", label: "Linux", icon: "🐧" },
      { id: "nginx", label: "Nginx", icon: "🌐" },
      { id: "vercel", label: "Vercel", icon: "▲" },
    ],
  },
];